services:
  go-backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-db
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: daniel@flockert.at
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    depends_on:
      - postgres-db

volumes:
  db_data:
