services:
  go-backend:
    build:
      context: .
    pull_policy: build
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

  adminer:
    build:
      context: ../adminer
      dockerfile: Dockerfile.adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db


volumes:
  db:
  uploads:
