services:
  go-backend:
    build:
      context: .
      args:
        GO_ENV: ${GO_ENV:-local}
    ports:
      - "8080:8080"
    env_file:
      - .env.${GO_ENV:-local}
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.${GO_ENV:-local}
    volumes:
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    env_file:
      - .env.${GO_ENV:-local}
    depends_on:
      - postgres-db

volumes:
  db:
  uploads:
