version: '3'

tasks:
  help:
    desc: Show help message
    cmds:
      - task --list

  run:
    desc: Run the Go application
    cmds:
      - go run .

  dev:
    desc: Run the Go application with hot reload
    cmds:
      - air -c .air.toml
  
  outdated:
    desc: Show outdated packages
    cmds:
      - go list -u -m all

  audit:
    desc: Security audit of dependencies
    cmds:
      - govulncheck ./...

  update:
    desc: Update all dependencies (minor and patch versions)
    cmds:
      - go get -u ./...
      - go mod tidy
