services:
  go-backend:
    build:
      context: ../backend
    pull_policy: build
    restart: always
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - postgres-db
    environment:
      - GO_ENV=${GO_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPENAPI_DOCS_USER=${OPENAPI_DOCS_USER}
      - OPENAPI_DOCS_PASSWORD=${OPENAPI_DOCS_PASSWORD}
    networks:
      - nginx-net

  postgres-db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - nginx-net

  adminer:
    build:
      context: ../adminer
      dockerfile: Dockerfile.adminer
    restart: always
    depends_on:
      - postgres-db
    networks:
      - nginx-net

volumes:
  db:
  uploads:
networks:
  nginx-net:
    external: true
