/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Alerts */
    get: operations['backend/handlers.(*DBWrapper).GetAlerts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/passkeys/login/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Start Passkey Login */
    post: operations['backend/handlers.(*DBWrapper).StartPasskeyLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/create-play-protocol-entry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Create Public Play Protocol Entry */
    post: operations['backend/handlers.(*DBWrapper).CreatePublicPlayProtocolEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My Account */
    get: operations['backend/handlers.(*DBWrapper).GetMyAccount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/auth/passkeys/register/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Start Passkey Registration */
    get: operations['backend/handlers.(*DBWrapper).StartPasskeyRegistration'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Change My Password */
    post: operations['backend/handlers.(*DBWrapper).ChangeMyPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/create-play-protocol-entry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Create My Play Protocol Entry */
    post: operations['backend/handlers.(*DBWrapper).CreateMyPlayProtocolEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My User Profile */
    get: operations['backend/handlers.(*DBWrapper).GetMyUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My Quizzes */
    get: operations['backend/handlers.(*DBWrapper).GetMyQuizzes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/allowed-file-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My Quizzes Allowed File Types */
    get: operations['backend/handlers.(*DBWrapper).GetMyQuizzesAllowedFileTypes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Create My Quiz */
    post: operations['backend/handlers.(*DBWrapper).CreateMyQuiz'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My Quiz */
    get: operations['backend/handlers.(*DBWrapper).GetMyQuiz'];
    put?: never;
    /** DB Wrapper Update My Quiz */
    post: operations['backend/handlers.(*DBWrapper).UpdateMyQuiz'];
    /** DB Wrapper Delete My Quiz */
    delete: operations['backend/handlers.(*DBWrapper).DeleteMyQuiz'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/{uuid}/trends': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get My Quiz Trends */
    get: operations['backend/handlers.(*DBWrapper).GetMyQuizTrends'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/quizzes/{uuid}/visibility': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Update My Quiz Visibility */
    post: operations['backend/handlers.(*DBWrapper).UpdateMyQuizVisibility'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/signout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Sign Out */
    post: operations['backend/handlers.(*DBWrapper).SignOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/update-image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Update My User Profile Image */
    post: operations['backend/handlers.(*DBWrapper).UpdateMyUserProfileImage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/upload/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Upload My File */
    post: operations['backend/handlers.(*DBWrapper).UploadMyFile'];
    /** DB Wrapper Delete My File */
    delete: operations['backend/handlers.(*DBWrapper).DeleteMyFile'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quizzes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Quizzes */
    get: operations['backend/handlers.(*DBWrapper).GetQuizzes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quizzes/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Quiz */
    get: operations['backend/handlers.(*DBWrapper).GetQuiz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Refresh Token */
    post: operations['backend/handlers.(*DBWrapper).RefreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Register */
    post: operations['backend/handlers.(*DBWrapper).Register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/seo/published-quizzes-uuids': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Seo Published Quizzes Uuids */
    get: operations['backend/handlers.(*DBWrapper).GetSeoPublishedQuizzesUuids'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Sign In */
    post: operations['backend/handlers.(*DBWrapper).SignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/{uuid}/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get User Profile */
    get: operations['backend/handlers.(*DBWrapper).GetUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HandlersChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    HandlersChangePasswordResponse: {
      message?: string;
    };
    HandlersCreatePlayProtocolEntryRequest: {
      quizUuid: string;
    };
    HandlersCreatePlayProtocolEntryWithUserRequest: {
      quizUuid: string;
    };
    HandlersCreateQuizRequest: {
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['HandlersCreateQuizRequestQuestion'][] | null;
      title: string;
    };
    HandlersCreateQuizRequestAnswer: {
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
    };
    HandlersCreateQuizRequestQuestion: {
      answers: components['schemas']['HandlersCreateQuizRequestAnswer'][];
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
    };
    HandlersDeleteFileResponse: {
      message: string;
    };
    HandlersGetAlertsResponse: {
      alerts: components['schemas']['ModelsAlert'][];
    };
    HandlersGetAllowedFileTypesResponse: {
      allowedAudioFileTypes: string;
      allowedImageFileTypes: string;
    };
    HandlersGetMyQuizTrendsResponse: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playProtocolStatistic: components['schemas']['HandlersGetMyQuizTrendsResponsePlayProtocolStatistic'];
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    HandlersGetMyQuizTrendsResponsePlayProtocolEntry: {
      migratedPlayCount: number | null;
      playCount: number | null;
      /** Format: date-time */
      playedAt: string;
    };
    HandlersGetMyQuizTrendsResponsePlayProtocolStatistic: {
      entriesPerDay: components['schemas']['HandlersGetMyQuizTrendsResponsePlayProtocolEntry'][];
      /** Format: date-time */
      migrationDate: string;
      playCount: number;
    };
    HandlersGetMyQuizzesResponse: {
      quizzes: components['schemas']['HandlersGetMyQuizzesResponseQuiz'][];
    };
    HandlersGetMyQuizzesResponseQuiz: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playCount: number;
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    HandlersGetMyUserProfileResponse: {
      quizStats: {
        totalQuizzesCreated: number;
        totalQuizzesPlayCount: number;
      };
      user: {
        /** Format: date-time */
        createdAt: string;
        profileImageUrl: string | null;
        username: string;
        uuid: string;
      };
    };
    HandlersGetPublicUserProfileResponse: {
      quizStats: {
        totalQuizzesCreated: number;
        totalQuizzesPlayCount: number;
      };
      user: {
        /** Format: date-time */
        createdAt: string;
        profileImageUrl: string | null;
        username: string;
        uuid: string;
      };
    };
    HandlersGetQuizResponse: {
      description: string;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['ModelsQuestion'][];
      title: string;
    };
    HandlersGetQuizzesResponse: {
      meta: components['schemas']['ModelsMeta'];
      quizzes: components['schemas']['HandlersGetQuizzesResponseQuiz'][];
    };
    HandlersGetQuizzesResponseQuiz: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playCount: number;
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      user: {
        username: string;
        uuid: string;
      };
      uuid: string;
    };
    HandlersPlayQuizResponse: {
      imageUrl: string | null;
      questions: components['schemas']['ModelsQuestion'][];
      title: string;
    };
    HandlersRefreshTokenRequest: {
      refreshToken: string;
    };
    HandlersRefreshTokenResponse: {
      accessToken: string;
    };
    HandlersRegisterRequest: {
      password: string;
      username: string;
    };
    HandlersRegisterResponse: {
      message?: string;
    };
    HandlersSignInRequest: {
      password: string;
      username: string;
    };
    HandlersSignInResponse: {
      accessToken: string;
      refreshToken: string;
      uuid: string;
    };
    HandlersSignOutRequest: {
      refreshToken: string;
    };
    HandlersStartPasskeyLoginRequest: {
      username: string;
    };
    HandlersUpdateQuizRequest: {
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['HandlersUpdateQuizRequestQuestion'][];
      title: string;
    };
    HandlersUpdateQuizRequestAnswer: {
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
      uuid: string | null;
    };
    HandlersUpdateQuizRequestQuestion: {
      answers: components['schemas']['HandlersUpdateQuizRequestAnswer'][];
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
      uuid: string | null;
    };
    HandlersUpdateQuizVisibilityRequest: {
      isPublished: boolean;
    };
    HandlersUpdateUserProfileImageRequest: {
      profileImageUrl: string | null;
    };
    HandlersUploadFileRequest: {
      /** Format: base64 */
      file: string;
      filename: string;
    };
    HandlersUploadFileResponse: {
      url: string;
    };
    ModelsAlert: {
      /** Format: date-time */
      createdAt: string;
      /** @enum {string|null} */
      imageSize: 'small' | 'medium' | 'large' | null;
      imageUrl: string | null;
      isActive: boolean;
      /** Format: markdown */
      markdownDe: string;
      /** Format: markdown */
      markdownEn: string;
      /** @enum {string} */
      severity: 'success' | 'info' | 'warning' | 'error';
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
      /** @enum {string} */
      visibleTo: 'everyone' | 'authorized';
    };
    ModelsAnswer: {
      /** Format: date-time */
      created_at: string;
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
      /** Format: date-time */
      updated_at: string;
      uuid: string;
    };
    ModelsMeta: {
      page: number;
      pageSize: number;
      totalItems: number;
      totalPages: number;
    };
    ModelsQuestion: {
      answers: components['schemas']['ModelsAnswer'][];
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    ModelsUserAccount: {
      /** Format: date-time */
      createdAt: string;
      isBlocked: boolean;
      isConfirmed: boolean;
      profileImageUrl: string | null;
      /** Format: date-time */
      updatedAt: string;
      username: string;
      uuid: string;
    };
    ProtocolAuthenticationExtensions: {
      [key: string]: unknown;
    };
    ProtocolAuthenticatorSelection: {
      authenticatorAttachment?: string;
      requireResidentKey?: boolean | null;
      residentKey?: string;
      userVerification?: string;
    };
    ProtocolCredentialAssertion: {
      mediation?: string;
      publicKey?: components['schemas']['ProtocolPublicKeyCredentialRequestOptions'];
    };
    ProtocolCredentialCreation: {
      mediation?: string;
      publicKey?: components['schemas']['ProtocolPublicKeyCredentialCreationOptions'];
    };
    ProtocolCredentialDescriptor: {
      id?: components['schemas']['ProtocolURLEncodedBase64'];
      transports?: string[];
      type?: string;
    };
    ProtocolCredentialParameter: {
      alg?: number;
      type?: string;
    };
    ProtocolPublicKeyCredentialCreationOptions: {
      attestation?: string;
      attestationFormats?: string[];
      authenticatorSelection?: components['schemas']['ProtocolAuthenticatorSelection'];
      challenge?: components['schemas']['ProtocolURLEncodedBase64'];
      excludeCredentials?: components['schemas']['ProtocolCredentialDescriptor'][];
      extensions?: components['schemas']['ProtocolAuthenticationExtensions'];
      hints?: string[];
      pubKeyCredParams?: components['schemas']['ProtocolCredentialParameter'][];
      rp?: components['schemas']['ProtocolRelyingPartyEntity'];
      timeout?: number;
      user?: components['schemas']['ProtocolUserEntity'];
    };
    ProtocolPublicKeyCredentialRequestOptions: {
      allowCredentials?: components['schemas']['ProtocolCredentialDescriptor'][];
      challenge?: components['schemas']['ProtocolURLEncodedBase64'];
      extensions?: components['schemas']['ProtocolAuthenticationExtensions'];
      hints?: string[];
      rpId?: string;
      timeout?: number;
      userVerification?: string;
    };
    ProtocolRelyingPartyEntity: {
      id?: string;
      name?: string;
    };
    ProtocolURLEncodedBase64: number[] | null;
    ProtocolUserEntity: {
      displayName?: string;
      id?: unknown;
      name?: string;
    };
    RestErrResponse: {
      /** @description Application-specific error code. */
      code?: number;
      /** @description Application context. */
      context?: {
        [key: string]: unknown;
      };
      /** @description Error message. */
      error?: string;
      /** @description Status text. */
      status?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'backend/handlers.(*DBWrapper).GetAlerts': {
    parameters: {
      query: {
        visibleTo: 'everyone' | 'authorized';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetAlertsResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).StartPasskeyLogin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersStartPasskeyLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProtocolCredentialAssertion'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).CreatePublicPlayProtocolEntry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreatePlayProtocolEntryRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyAccount': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelsUserAccount'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).StartPasskeyRegistration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProtocolCredentialCreation'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).ChangeMyPassword': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersChangePasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersChangePasswordResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).CreateMyPlayProtocolEntry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreatePlayProtocolEntryWithUserRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyUserProfile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyUserProfileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyQuizzes': {
    parameters: {
      query: {
        sortOption: 'createdAt' | 'playCount';
        sortDirection: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyQuizzesResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyQuizzesAllowedFileTypes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetAllowedFileTypesResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).CreateMyQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreateQuizRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetQuizResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).UpdateMyQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateQuizRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).DeleteMyQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetMyQuizTrends': {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyQuizTrendsResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).UpdateMyQuizVisibility': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateQuizVisibilityRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).SignOut': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersSignOutRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).UpdateMyUserProfileImage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateUserProfileImageRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).UploadMyFile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUploadFileRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersUploadFileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).DeleteMyFile': {
    parameters: {
      query: {
        filename: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersDeleteFileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetQuizzes': {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortOption: 'createdAt' | 'playCount';
        sortDirection: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetQuizzesResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersPlayQuizResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).RefreshToken': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersRefreshTokenRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersRefreshTokenResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).Register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersRegisterRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersRegisterResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetSeoPublishedQuizzesUuids': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).SignIn': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersSignInRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersSignInResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetUserProfile': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetPublicUserProfileResponse'];
        };
      };
    };
  };
}
