/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/a/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Change Password */
    post: operations['backend/handlers.(*DBWrapper).HandleChangePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/my-quizzes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get My Quizzes */
    get: operations['backend/handlers.(*DBWrapper).HandleGetMyQuizzes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/my-user-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get My User Profile */
    get: operations['backend/handlers.(*DBWrapper).HandleGetMyUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/passkey/generate-registration-options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Passkey Registration Options */
    get: operations['backend/handlers.(*DBWrapper).HandlePasskeyRegistrationOptions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/play-protocol-entry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Create Play Protocol Entry With User */
    post: operations['backend/handlers.(*DBWrapper).HandleCreatePlayProtocolEntryWithUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/quiz/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Create Quiz */
    post: operations['backend/handlers.(*DBWrapper).HandleCreateQuiz'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/quiz/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get Quiz */
    get: operations['backend/handlers.(*DBWrapper).HandleGetQuiz'];
    put?: never;
    /** DB Wrapper Handle Update Quiz */
    post: operations['backend/handlers.(*DBWrapper).HandleUpdateQuiz'];
    /** DB Wrapper Handle Delete Quiz */
    delete: operations['backend/handlers.(*DBWrapper).HandleDeleteQuiz'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/quiz/{uuid}/trends': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get My Quiz Trends */
    get: operations['backend/handlers.(*DBWrapper).HandleGetMyQuizTrends'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/quiz/{uuid}/visibility': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Update Quiz Visibility */
    post: operations['backend/handlers.(*DBWrapper).HandleUpdateQuizVisibility'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/signout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Sign Out */
    post: operations['backend/handlers.(*DBWrapper).HandleSignOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/update-profile-image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Update User Profile Image */
    post: operations['backend/handlers.(*DBWrapper).HandleUpdateUserProfileImage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Upload File */
    post: operations['backend/handlers.(*DBWrapper).HandleUploadFile'];
    /** DB Wrapper Handle Delete File */
    delete: operations['backend/handlers.(*DBWrapper).HandleDeleteFile'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/a/user-account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get User Account */
    get: operations['backend/handlers.(*DBWrapper).HandleGetUserAccount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get Alerts */
    get: operations['backend/handlers.(*DBWrapper).HandleGetAlerts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/allowed-file-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get Allowed File Types */
    get: operations['backend/handlers.(*DBWrapper).HandleGetAllowedFileTypes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/play-protocol-entry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Create Play Protocol Entry */
    post: operations['backend/handlers.(*DBWrapper).HandleCreatePlayProtocolEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/play/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Handle Play Quiz */
    get: operations['backend/handlers.(*DBWrapper).HandleHandlePlayQuiz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quizzes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get Quizzes */
    get: operations['backend/handlers.(*DBWrapper).HandleGetQuizzes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Refresh Token */
    post: operations['backend/handlers.(*DBWrapper).HandleRefreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Register */
    post: operations['backend/handlers.(*DBWrapper).HandleRegister'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/signin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** DB Wrapper Handle Sign In */
    post: operations['backend/handlers.(*DBWrapper).HandleSignIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user-profile/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Handle Get Public User Profile */
    get: operations['backend/handlers.(*DBWrapper).HandleGetPublicUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HandlersChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    HandlersChangePasswordResponse: {
      message?: string;
    };
    HandlersCreatePlayProtocolEntryRequest: {
      quizUuid: string;
    };
    HandlersCreatePlayProtocolEntryWithUserRequest: {
      quizUuid: string;
    };
    HandlersCreateQuizRequest: {
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['HandlersCreateQuizRequestQuestion'][] | null;
      title: string;
    };
    HandlersCreateQuizRequestAnswer: {
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
    };
    HandlersCreateQuizRequestQuestion: {
      answers: components['schemas']['HandlersCreateQuizRequestAnswer'][];
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
    };
    HandlersDeleteFileResponse: {
      message: string;
    };
    HandlersGetAlertsResponse: {
      alerts: components['schemas']['ModelsAlert'][];
    };
    HandlersGetAllowedFileTypesResponse: {
      allowedAudioFileTypes: string;
      allowedImageFileTypes: string;
    };
    HandlersGetMyQuizTrendsResponse: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playProtocolStatistic: components['schemas']['HandlersGetMyQuizTrendsResponsePlayProtocolStatistic'];
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    HandlersGetMyQuizTrendsResponsePlayProtocolEntry: {
      migratedPlayCount: number | null;
      playCount: number | null;
      /** Format: date-time */
      playedAt: string;
    };
    HandlersGetMyQuizTrendsResponsePlayProtocolStatistic: {
      entriesPerDay: components['schemas']['HandlersGetMyQuizTrendsResponsePlayProtocolEntry'][];
      /** Format: date-time */
      migrationDate: string;
      playCount: number;
    };
    HandlersGetMyQuizzesResponse: {
      quizzes: components['schemas']['HandlersGetMyQuizzesResponseQuiz'][];
    };
    HandlersGetMyQuizzesResponseQuiz: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playCount: number;
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    HandlersGetMyUserProfileResponse: {
      quizStats: {
        totalQuizzesCreated: number;
        totalQuizzesPlayCount: number;
      };
      user: {
        /** Format: date-time */
        createdAt: string;
        profileImageUrl: string | null;
        username: string;
        uuid: string;
      };
    };
    HandlersGetPublicUserProfileResponse: {
      quizStats: {
        totalQuizzesCreated: number;
        totalQuizzesPlayCount: number;
      };
      user: {
        /** Format: date-time */
        createdAt: string;
        profileImageUrl: string | null;
        username: string;
        uuid: string;
      };
    };
    HandlersGetQuizResponse: {
      description: string;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['ModelsQuestion'][];
      title: string;
    };
    HandlersGetQuizzesResponse: {
      meta: components['schemas']['ModelsMeta'];
      quizzes: components['schemas']['HandlersGetQuizzesResponseQuiz'][];
    };
    HandlersGetQuizzesResponseQuiz: {
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      playCount: number;
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      user: {
        username: string;
        uuid: string;
      };
      uuid: string;
    };
    HandlersPasskeyRegistrationOptionsResponse: {
      mediation?: string;
      publicKey?: components['schemas']['ProtocolPublicKeyCredentialCreationOptions'];
    };
    HandlersPlayQuizResponse: {
      imageUrl: string | null;
      questions: components['schemas']['ModelsQuestion'][];
      title: string;
    };
    HandlersRefreshTokenRequest: {
      refreshToken: string;
    };
    HandlersRefreshTokenResponse: {
      accessToken: string;
    };
    HandlersRegisterRequest: {
      password: string;
      username: string;
    };
    HandlersRegisterResponse: {
      message?: string;
    };
    HandlersSignInRequest: {
      password: string;
      username: string;
    };
    HandlersSignInResponse: {
      accessToken: string;
      refreshToken: string;
      uuid: string;
    };
    HandlersSignOutRequest: {
      refreshToken: string;
    };
    HandlersUpdateQuizRequest: {
      description: string | null;
      imageUrl: string | null;
      isPublished: boolean;
      questions: components['schemas']['HandlersUpdateQuizRequestQuestion'][];
      title: string;
    };
    HandlersUpdateQuizRequestAnswer: {
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
      uuid: string | null;
    };
    HandlersUpdateQuizRequestQuestion: {
      answers: components['schemas']['HandlersUpdateQuizRequestAnswer'][];
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
      uuid: string | null;
    };
    HandlersUpdateQuizVisibilityRequest: {
      isPublished: boolean;
    };
    HandlersUpdateUserProfileImageRequest: {
      profileImageUrl: string | null;
    };
    HandlersUploadFileRequest: {
      /** Format: base64 */
      file: string;
      filename: string;
    };
    HandlersUploadFileResponse: {
      url: string;
    };
    ModelsAlert: {
      /** Format: date-time */
      createdAt: string;
      /** @enum {string|null} */
      imageSize: 'small' | 'medium' | 'large' | null;
      imageUrl: string | null;
      isActive: boolean;
      /** Format: markdown */
      markdownDe: string;
      /** Format: markdown */
      markdownEn: string;
      /** @enum {string} */
      severity: 'success' | 'info' | 'warning' | 'error';
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
      /** @enum {string} */
      visibleTo: 'everyone' | 'authorized';
    };
    ModelsAnswer: {
      /** Format: date-time */
      created_at: string;
      description: string | null;
      imageUrl: string | null;
      isCorrect: boolean;
      title: string;
      /** Format: date-time */
      updated_at: string;
      uuid: string;
    };
    ModelsMeta: {
      page: number;
      pageSize: number;
      totalItems: number;
      totalPages: number;
    };
    ModelsQuestion: {
      answers: components['schemas']['ModelsAnswer'][];
      /** Format: date-time */
      createdAt: string;
      description: string | null;
      explanation: string | null;
      explanationImageUrl: string | null;
      imageUrl: string | null;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
    ModelsUserAccount: {
      /** Format: date-time */
      createdAt: string;
      isBlocked: boolean;
      isConfirmed: boolean;
      profileImageUrl: string | null;
      /** Format: date-time */
      updatedAt: string;
      username: string;
      uuid: string;
    };
    ProtocolAuthenticationExtensions: {
      [key: string]: unknown;
    };
    ProtocolAuthenticatorSelection: {
      authenticatorAttachment?: string;
      requireResidentKey?: boolean | null;
      residentKey?: string;
      userVerification?: string;
    };
    ProtocolCredentialDescriptor: {
      id?: components['schemas']['ProtocolURLEncodedBase64'];
      transports?: string[];
      type?: string;
    };
    ProtocolCredentialParameter: {
      alg?: number;
      type?: string;
    };
    ProtocolPublicKeyCredentialCreationOptions: {
      attestation?: string;
      attestationFormats?: string[];
      authenticatorSelection?: components['schemas']['ProtocolAuthenticatorSelection'];
      challenge?: components['schemas']['ProtocolURLEncodedBase64'];
      excludeCredentials?: components['schemas']['ProtocolCredentialDescriptor'][];
      extensions?: components['schemas']['ProtocolAuthenticationExtensions'];
      hints?: string[];
      pubKeyCredParams?: components['schemas']['ProtocolCredentialParameter'][];
      rp?: components['schemas']['ProtocolRelyingPartyEntity'];
      timeout?: number;
      user?: components['schemas']['ProtocolUserEntity'];
    };
    ProtocolRelyingPartyEntity: {
      id?: string;
      name?: string;
    };
    ProtocolURLEncodedBase64: number[] | null;
    ProtocolUserEntity: {
      displayName?: string;
      id?: unknown;
      name?: string;
    };
    RestErrResponse: {
      /** @description Application-specific error code. */
      code?: number;
      /** @description Application context. */
      context?: {
        [key: string]: unknown;
      };
      /** @description Error message. */
      error?: string;
      /** @description Status text. */
      status?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'backend/handlers.(*DBWrapper).HandleChangePassword': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersChangePasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersChangePasswordResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetMyQuizzes': {
    parameters: {
      query: {
        sortOption: 'createdAt' | 'playCount';
        sortDirection: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyQuizzesResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetMyUserProfile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyUserProfileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandlePasskeyRegistrationOptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersPasskeyRegistrationOptionsResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleCreatePlayProtocolEntryWithUser': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreatePlayProtocolEntryWithUserRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleCreateQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreateQuizRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetQuizResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleUpdateQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateQuizRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleDeleteQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetMyQuizTrends': {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetMyQuizTrendsResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleUpdateQuizVisibility': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateQuizVisibilityRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleSignOut': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersSignOutRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleUpdateUserProfileImage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUpdateUserProfileImageRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleUploadFile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersUploadFileRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersUploadFileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleDeleteFile': {
    parameters: {
      query: {
        filename: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersDeleteFileResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetUserAccount': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelsUserAccount'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RestErrResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetAlerts': {
    parameters: {
      query: {
        visibleTo: 'everyone' | 'authorized';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetAlertsResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetAllowedFileTypes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetAllowedFileTypesResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleCreatePlayProtocolEntry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersCreatePlayProtocolEntryRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleHandlePlayQuiz': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersPlayQuizResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetQuizzes': {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortOption: 'createdAt' | 'playCount';
        sortDirection: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetQuizzesResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleRefreshToken': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersRefreshTokenRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersRefreshTokenResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleRegister': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersRegisterRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersRegisterResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleSignIn': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['HandlersSignInRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersSignInResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).HandleGetPublicUserProfile': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersGetPublicUserProfileResponse'];
        };
      };
    };
  };
}
