/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/quiz/{uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Quiz By Uuid */
    get: operations['backend/handlers.(*DBWrapper).GetQuizByUuid'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/quizzes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB Wrapper Get Quizzes */
    get: operations['backend/handlers.(*DBWrapper).GetQuizzes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HandlersQuiz: {
      /** Format: date-time */
      createdAt: string;
      description?: string | null;
      imageUrl?: string | null;
      isPublished: boolean;
      playCount: number;
      questionCount: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      user: {
        username: string;
        uuid: string;
      };
      uuid: string;
    };
    HandlersReponse: {
      quizzes: components['schemas']['HandlersQuiz'][];
    };
    HandlersResponse: {
      imageUrl?: string;
      questions: components['schemas']['ModelsQuestion'][];
      title: string;
    };
    ModelsAnswer: {
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      imageUrl?: string | null;
      isCorrect: boolean;
      title: string;
      /** Format: date-time */
      updated_at: string;
      uuid: string;
    };
    ModelsQuestion: {
      answers: components['schemas']['ModelsAnswer'][];
      /** Format: date-time */
      createdAt: string;
      description?: string | null;
      explanation?: string | null;
      explanationImageUrl?: string | null;
      imageUrl?: string | null;
      title: string;
      /** Format: date-time */
      updatedAt: string;
      uuid: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'backend/handlers.(*DBWrapper).GetQuizByUuid': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersResponse'];
        };
      };
    };
  };
  'backend/handlers.(*DBWrapper).GetQuizzes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HandlersReponse'];
        };
      };
    };
  };
}
