services:
  quizio-strapi:
    image: my-quiz-backend-quizio-strapi
    build: .
    restart: always
    networks:
      - nginx-net
    volumes:
      - strapidb:/opt/app/.tmp
      - strapiuploads:/opt/app/public/uploads
    env_file:
      - .env
volumes:
  strapidb:
  strapiuploads:
networks:
  nginx-net:
    external: true
