version: '3'
services:
  quizio-strapi:
    build: .
    restart: always
    networks:
      - nginx-net
    volumes:
      - my-quiz-backend_strapidb:/opt/app/.tmp
      - my-quiz-backend_strapiuploads:/opt/app/public/uploads
    env_file:
      - .env
volumes:
  my-quiz-backend_strapidb:
  my-quiz-backend_strapiuploads:
networks:
  nginx-net:
    external: true
