version: '3'

dotenv: ['../backend/.env.local']

tasks:
  help:
    desc: Show help message
    cmds:
      - task --list

  psql:
    desc: Connect to PostgreSQL database
    cmds:
      - PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB {{.CLI_ARGS}}

  migrate-up:
    desc: Applies all migrations to the database
    cmds:
      - migrate -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable -path migrations up
  
  migrate-down:
    desc: Undos all migrations from the database
    cmds:
      - migrate -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable -path migrations down

  migrate-set-version:
    desc: Sets the migration version with force
    cmds:
      - migrate -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB?sslmode=disable -path migrations force {{.CLI_ARGS}}

  create-migration:
    desc: Creates a migration. e.g. task create-migration -- <migration-name>
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}
