services:
  quizio-strapi:
    build: .
    restart: always
    ports:
      - 1337:1337
    volumes:
      - strapidb:/opt/app/.tmp
      - strapiuploads:/opt/app/public/uploads
    env_file:
      - .env
volumes:
  strapidb:
  strapiuploads:
