name: Adminer - Build and Push Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "adminer/**"
      - "infra/**"
  pull_request:
    branches: ["main"]
    paths:
      - "adminer/**"
      - "infra/**"
  workflow_dispatch:

jobs:
  build-adminer:
    name: Build & Push Adminer Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Adminer Image
        run: |
          docker build -t ghcr.io/rathalin/quizio/adminer:latest ./adminer
          docker push ghcr.io/rathalin/quizio/adminer:latest
